spring:
  datasource:
    url: jdbc:h2:mem:taxi-service-db
    driver-class-name: org.h2.Driver
    username: u
    password: u

  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console

  sql:
    init:
      mode: always

server:
  port: 8080
